export const profileInfoConstant = {
  profilePercentage: "% profile is completed",
  employeeId: "employee ID",
  emailId: "email ID",
  department: "department",
  designation: "designation",
  dateOfJoining: "date of joining",
  reportingManager: "reporting to",
  dob: "DOB",
  tabs: {
    personal: "personal",
    professional: "professional",
    skills: "skills and qualifications",
  },
  departmentDropdown: ["developer", "product", "human-resource", "accounts"],
  designationDropdown: [
    "Trainee",
    "Manager",
    "Intern",
    "Jr Developer",
    "Sr Developer",
    "Tech Lead",
    "Product Owner",
    "Project Manager",
    "Scrum Master",
    "HR Executive",
    "Leader",
  ],
};
